name       : lua51
version    : 5.1.5
release    : 4
source     :
    - http://www.lua.org/ftp/lua-5.1.5.tar.gz : 2640fc56a795f29d28ef15e13c34a47e223960b0240e8cb0a82d9b0738695333
license    : MIT
component  : programming
summary    : Lightweight programming language
description: |
    Lua is a powerful light-weight programming language designed for extending applications. It is also frequently used as a general-purpose, stand-alone language. Lua is implemented as a small library of C functions, written in ANSI C, and compiles unmodified in all known platforms. The implementation goals are simplicity, efficiency, portability, and low embedding cost. The result is a fast language engine with small footprint, making it ideal in embedded systems too.
patterns   :
    - devel : [/usr/bin]
setup      : |
    unset LD_AS_NEEDED
    %patch -p1 < $pkgfiles/0001-Ensure-unique-lua-5.1-shared-objects-and-use-correct.patch
    %patch -p1 < $pkgfiles/security/cve-2014-5461.patch
build      : |
    unset LD_AS_NEEDED
    %make linux
install    : |
    unset LD_AS_NEEDED
    %make_install \
        INSTALL_TOP=$installdir/usr \
        INSTALL_DATA="cp -d" \
        INSTALL_INC=$installdir/usr/include/lua5.1 \
        INSTALL_MAN=$installdir/usr/share/man/man1
    install -Dm00644 $pkgfiles/lua-5.1.pc $installdir/usr/lib/pkgconfig/lua-5.1.pc
